development:
  stripe_secret_key: sk_test_aAmStsWDo0lkgWAG8O6M45g4
  stripe_public_key: pk_test_yEFNNePi1eXS0zhIAtXOKM4F
  captcha_secret_key: 6Le0214UAAAAAM3Bz4N-SxgtUkO0j95jxrq8aTgd
  captcha_public_key: 6Le0214UAAAAAJjlTiLEA0zKG2KODjcYXVMdMZsP
